services:
  backend:
    build: .
    container_name: hr_ai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./candidats:/app/candidats
      - ./modele:/app/modele
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: hr_ai_frontend
    ports:
      - "3000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./image:/usr/share/nginx/html/image
    restart: unless-stopped